#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfontsel
Version  : 1.0.6
Release  : 1
URL      : https://www.x.org/releases/individual/app/xfontsel-1.0.6.tar.gz
Source0  : https://www.x.org/releases/individual/app/xfontsel-1.0.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT X11
Requires: xfontsel-bin = %{version}-%{release}
Requires: xfontsel-data = %{version}-%{release}
Requires: xfontsel-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xaw7)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xt)

%description
xfontsel application provides a simple way to display the X11 core
protocol fonts known to your X server, examine samples of each, and
retrieve the X Logical Font Description ("XLFD") full name for a font.

%package bin
Summary: bin components for the xfontsel package.
Group: Binaries
Requires: xfontsel-data = %{version}-%{release}
Requires: xfontsel-man = %{version}-%{release}

%description bin
bin components for the xfontsel package.


%package data
Summary: data components for the xfontsel package.
Group: Data

%description data
data components for the xfontsel package.


%package man
Summary: man components for the xfontsel package.
Group: Default

%description man
man components for the xfontsel package.


%prep
%setup -q -n xfontsel-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550613861
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550613861
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xfontsel

%files data
%defattr(-,root,root,-)
/usr/share/X11/app-defaults/XFontSel

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xfontsel.1
